version: 2

pip_install: &pip_install
  name: Pipenv Install
  command: |
    set -e
    pipenv update
    pipenv install --dev
    . $(pipenv --venv)/bin/activate

jobs:
  init:
    working_directory: ~/grow
    docker:
      - image: grow/grow-internal-image
    steps:
      - checkout

      - restore_cache:
          key: ui-{{ .Branch }}-{{ checksum "grow/ui/package.json" }}

      - run:
          name: Build UI
          command: make build-ui

      - save_cache:
          key: ui-{{ .Branch }}-{{ checksum "grow/ui/package.json" }}
          paths:
            - "grow/ui/node_modules"

      - persist_to_workspace:
          root: ~/grow
          paths:
            - .coveragerc
            - .git/*
            - bin/*
            - grow/*
            - scripts/*
            - description.txt
            - grow.spec
            - install.py
            - Makefile
            - MANIFEST.in
            - package.json
            - pylintrc
            - requirements-dev.txt
            - requirements.txt
            - Pipfile
            - Pipfile.lock
            - setup.py

  pylint:
    working_directory: ~/grow
    docker:
      - image: grow/grow-internal-image
    steps:
      - attach_workspace:
          at: ~/grow

      - restore_cache:
          key: pip-{{ .Branch }}-{{ checksum "Pipfile" }}-{{ checksum "Pipfile.lock" }}

      - run:
          <<: *pip_install

      - save_cache:
          key: pip-{{ .Branch }}-{{ checksum "Pipfile" }}-{{ checksum "Pipfile.lock" }}
          paths:
          - /root/.local/share/virtualenvs/

      - run:
          name: Pylint
          command: make test-pylint

  release-package-linux:
    working_directory: ~/grow
    docker:
      - image: grow/grow-internal-image
    steps:
      - attach_workspace:
          at: ~/grow

      - restore_cache:
          key: pip-release-linux-{{ .Branch }}-{{ checksum "Pipfile" }}-{{ checksum "Pipfile.lock" }}

      - run:
          <<: *pip_install

      - save_cache:
          key: pip-release-linux-{{ .Branch }}-{{ checksum "Pipfile" }}-{{ checksum "Pipfile.lock" }}
          paths:
          - /root/.local/share/virtualenvs/

      - run:
          name: Build Release
          command: pyinstaller grow.spec

      - run:
          name: Package
          command: |
            set -e
            cd dist
            zip -r "Grow-SDK-Linux-${CIRCLE_TAG}.zip" grow
            cd ..

      # Currently causes a seg fault in docker.
      # - run:
      #     name: Test Packaged Grow
      #     command: ./dist/grow
      #
      # - run:
      #     name: Test Packaged Grow Build
      #     command: ./dist/grow build ./grow/testing/testdata/pod

      - run:
          name: Upload to GitHub
          command: ghr -draft -u grow $CIRCLE_TAG "dist/Grow-SDK-Linux-${CIRCLE_TAG}.zip"

      - store_artifacts:
          path: dist/

  release-package-osx:
    working_directory: ~/grow
    macos:
      xcode: "9.0"
    steps:
      - attach_workspace:
          at: ~/grow

      - run:
          name: Install Go
          command: brew install golang

      - run:
          name: Update GOROOT
          command: echo 'export GOROOT=/usr/local/opt/go/libexec' >> $BASH_ENV
      - run:
          name: Update GOPATH
          command: echo 'export GOPATH=$HOME/gocode' >> $BASH_ENV
      - run:
          name: Update PATH
          command: echo 'export PATH=$PATH:$GOROOT/bin:$GOPATH/bin' >> $BASH_ENV

      - run:
          name: Install ghr
          command: go get -u github.com/tcnksm/ghr

      - restore_cache:
          key: pip-release-osx-{{ .Branch }}-{{ checksum "Pipfile" }}-{{ checksum "Pipfile.lock" }}

      - run:
          <<: *pip_install

      - save_cache:
          key: pip-release-osx-{{ .Branch }}-{{ checksum "Pipfile" }}-{{ checksum "Pipfile.lock" }}
          paths:
          - /Users/distiller/.local/share/virtualenvs/

      - run:
          name: Build Release
          command: pyinstaller grow.spec

      - run:
          name: Package
          command: |
            set -e
            cd dist
            zip -r "Grow-SDK-Mac-${CIRCLE_TAG}.zip" grow
            cd ..

      - run:
          name: Test Packaged Grow
          command: ./dist/grow

      - run:
          name: Test Packaged Grow Build
          command: ./dist/grow build ./grow/testing/testdata/pod

      - run:
          name: Upload to GitHub
          command: ghr -draft -u grow $CIRCLE_TAG "dist/Grow-SDK-Mac-${CIRCLE_TAG}.zip"

      - store_artifacts:
          path: dist/

  release-package-pypi:
    working_directory: ~/grow
    docker:
      - image: grow/grow-internal-image
    steps:
      - attach_workspace:
          at: ~/grow

      - restore_cache:
          key: pip-{{ .Branch }}-{{ checksum "Pipfile" }}-{{ checksum "Pipfile.lock" }}

      - run:
          <<: *pip_install

      - save_cache:
          key: pip-{{ .Branch }}-{{ checksum "Pipfile" }}-{{ checksum "Pipfile.lock" }}
          paths:
          - /root/.local/share/virtualenvs/

      - run:
          name: Create Distribution
          command: python setup.py sdist bdist_wheel

      - run:
          name: Pip Install
          command: |
            set -e
            pip install urllib3[secure] --upgrade
            pip install twine --upgrade

      - run:
          name: Twine Upload
          command: twine upload dist/grow-$(<grow/VERSION)*

      - store_artifacts:
          path: dist/

  test:
    working_directory: ~/grow
    docker:
      - image: grow/grow-internal-image
    steps:
      - attach_workspace:
          at: ~/grow

      - restore_cache:
          key: pip-{{ .Branch }}-{{ checksum "Pipfile" }}-{{ checksum "Pipfile.lock" }}

      - run:
          <<: *pip_install

      - save_cache:
          key: pip-{{ .Branch }}-{{ checksum "Pipfile" }}-{{ checksum "Pipfile.lock" }}
          paths:
          - /root/.local/share/virtualenvs/

      - run:
          name: Run Tests
          command: make test-nosetests

      - run:
          name: Code Coverage
          command: $(pipenv --venv)/bin/codecov

      - run:
          name: Test build
          command: ./scripts/grow build ./grow/testing/testdata/pod

  test-osx:
    working_directory: ~/grow
    macos:
      xcode: "9.0"
    steps:
      - attach_workspace:
          at: ~/grow

      - run:
          name: Install pipenv
          command: brew install pipenv

      - restore_cache:
          key: pip-osx-{{ .Branch }}-{{ checksum "Pipfile" }}-{{ checksum "Pipfile.lock" }}

      - run:
          <<: *pip_install

      - save_cache:
          key: pip-osx-{{ .Branch }}-{{ checksum "Pipfile" }}-{{ checksum "Pipfile.lock" }}
          paths:
          - /Users/distiller/.local/share/virtualenvs/

      - run:
          name: Run Tests
          command: make test-nosetests

      - run:
          name: Code Coverage
          command: $(pipenv --venv)/bin/codecov

      - run:
          name: Test build
          command: ./scripts/grow build ./grow/testing/testdata/pod

filter_all_tags: &filter_all_tags
  filters:
    tags:
      only: /.*/

filter_only_tags: &filter_only_tags
  filters:
    tags:
      only: /.*/
    branches:
      ignore: /.*/

workflows:
  version: 2
  build:
    jobs:
    - init:
        <<: *filter_all_tags
    - pylint:
        <<: *filter_all_tags
        requires:
        - init
    - test:
        <<: *filter_all_tags
        requires:
        - init
    - test-osx:
        <<: *filter_all_tags
        requires:
        - init
    - release-package-linux:
        <<: *filter_only_tags
        requires:
        - test
    - release-package-osx:
        <<: *filter_only_tags
        requires:
        - test-osx
    - release-package-pypi:
        <<: *filter_only_tags
        requires:
        - release-package-linux
        - release-package-osx
